### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by mkatliar**
Several improvements have been made, here are the main ones:
* RAII-based subscription management
* Return codes replaced by exception-based error handling in many places
* Interfaces of `RWSClient` and `RWSInterface` made more usable
* Removed unnecessary class nesting in some places when it makes sense
* Merged functionality to add/remove modules to tasks
* Added `ZoneData` class
* Using `override` keyword when appropriate
* Improved const-correctness

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR :+1: much appreciated.

I've skimmed through the commits and there are indeed quite a few very nice improvements.

Both @jontje and I are unfortunately busy, so a proper review will take some time.

Lame excuse, I know :(, but I can't make it any better than it is.

Please know that tardy response does not mean lack of interest or appreciation.

**Comment by gavanderhoorn** [comment]
I noticed you appear to have #127 in here (and possibly some of the others).

Not sure we should merge those as part of this PR.

**Comment by mkatliar** [comment]
> I noticed you appear to have #127 in here (and possibly some of the others).
> 
> Not sure we should merge those as part of this PR.

I just checked it and I don't have #127 merged in my PR.

**Comment by mkatliar** [comment]
Superceded by #136 (using a stable source branch).

**Pull request closed without merging**
