### PR TITLE
Added a section for usage hints, replaced an obsolete interface 

### PR DESCRIPTION
**Pull request by jontje**
* Added brief descriptions of the library's primary classes.
* Added references to an optional RobotWare Add-In called StateMachine Add-In.
* Replaced the obsolete RWSSimpleStateMachineInterface with RWSStateMachineInterface.
* Generalized the RAPID representation with name change and added a class representing a RAPID record of type speeddata.

### CODE REVIEW

**Comment by jontje** [comment]
I forgot to mention that this PR is related to issues https://github.com/ros-industrial/abb_librws/issues/20 and https://github.com/ros-industrial/abb_librws/issues/29

**Comment by gavanderhoorn** [comment]
General comment: could I ask you to please use multiple commits for these kind of PRs? We're now changing documentation, code and build scripts in a single commit. Apart from that being not very clean, it's also logistically difficult now to revert changes to any of these categories of files without having to use tricks with the other files.

If the changes were in separate commits it would be relatively trivial to manage them.

Just something for the future.

**Comment by jontje** [comment]
You are completely right, I didn't even think about that. I will remember it for the future.

**Comment by gavanderhoorn** [comment]
Should d358848 be part of a separate PR?

(similar comment as https://github.com/ros-industrial/abb_librws/pull/32#issuecomment-442966104).

**Comment by jontje** [comment]
Yeah, you are right :) I was a bit hasty yesterday, I will close this PR and split it into smaller ones

**Pull request closed without merging**
