### PR TITLE
switch to new version of industrial_ci

### PR DESCRIPTION
**Pull request by ipa-mdl**
https://github.com/ros-industrial/industrial_ci/issues/390

### CODE REVIEW

**Comment by ipa-mdl** [comment]
https://github.com/ros-industrial/abb_librws/pull/56/commits/af1639f04b9bddf3692eac6cc991d35ce84e893b could get reverted later

**Comment by gavanderhoorn** [comment]
@ipa-mdl: would you recommend we merge this PR in here?

Are you satisfied with the stability of the new version or are there changes you'd like to integrate before switching over?

**Comment by ipa-mdl** [comment]
> would you recommend we merge this PR in here?

for now it is a beta version, it's up to the maintainer

> Are you satisfied with the stability of the new version

I would say it is stable, I don't expect any breaking changes.

> are there changes you'd like to integrate before switching over?

I'd like to refactor it even further, but mostly under the hood.

**Comment by gavanderhoorn** [comment]
Some of this seems to be included in #69.

After merging that PR, we should see which parts of this one are still relevant.

**Comment by gavanderhoorn** [comment]
Seems the changes in this PR were merged in parts by #57 and #69.

We're using `master` of `industrial_ci` here now.

Thanks @ipa-mdl for the initial PR and thanks for your continued support for `industrial_ci` :+1: :hamburger: :beers:

**Pull request closed without merging**
