### PR TITLE
Take args by const reference where useful.

### PR DESCRIPTION
**Pull request by de-vri-es**
This PR does a couple of things:
* It removes trailing whitespace.
* It takes arguments by `const &` where useful (like `std::string` or objects containing strings).
* It makes the project pass `-Wall -Wextra -Wpedantic` without warnings:
  * A loop counter as signed integer caused signed/unsigned comparison.
  * `TriBool` had a manual copy assignment operator, but not a manual copy constructor.

The arguments by const & is the most important part of the PR, as it can lead to actual performance improvement.

Note that in some cases, for constructors, taking objects by value and moving them into members would be even more efficient, but that would mean requiring C++11. It looked like the project doesn't require that yet, so I decided not to go for that.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Just noticed: this would fix #13.

**Comment by gavanderhoorn** [comment]
Thanks for the PR :+1: . Unfortunately reviewing and merging it is going to take some time, as both me and @jontje have a very busy few weeks ahead of us.

**Comment by de-vri-es** [comment]
Thanks for the review. I applied your suggestions and rebased on current master.
 
> FYI, the code style of this library has primarily been based on the [ROS C++ Style Guide](http://wiki.ros.org/CppStyleGuide), which specify a maximum line length of 120 characters. I don’t think this is mentioned anywhere, so it’s impossible for you to know.

I generally try to guess style rules from the surrounding code, but I may accidentally revert to my own preferences now and then. Good thing the review caught it :)

**Comment by jontje** [comment]
> I generally try to guess style rules from the surrounding code, but I may accidentally revert to my own preferences now and then. Good thing the review caught it :)

No worries, and I try to at least be semi-pedantic when reviewing;)

**Pull request merged**
