### PR TITLE
Collect arm cfg instances

### PR DESCRIPTION
**Pull request by jontje**
As per title

### CODE REVIEW

**Review by gavanderhoorn — APPROVED** [review]
Nice. Thanks for adding the checks :+1:

**Comment by jontje** [comment]
> Similar high-level comment as the other PRs: there doesn't appear to be any explicit error handling.
> 
> Can things not fail?

I have added some error handling in 8062aa4, and that approch is acceptable, then I will add it to the other PRs.

As a side note, I first used `constexpr` for the error messages, but since it is for C++11 I replaced it with `static const` in 6ea0605. Also, when ROS Kinetic reaches EOL, then I will try to find some time to use e.g. auto and range-based for loops, which could cleanup the parsing of configuration instances alot.

**Comment by gavanderhoorn** [comment]
We don't need to wait on Kinetic EOL for that: C++11 can be used with Kinetic nodes.

**Comment by jontje** [comment]
Thanks for the review @gavanderhoorn 👍 

> We don't need to wait on Kinetic EOL for that: C++11 can be used with Kinetic nodes.

And thanks for this clarification as well.

**Pull request merged**
