### PR TITLE
Migrate to Github actions

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This removes Travis and sets up a basic GHA workflow.

We keep the Windows workflow and add two Ubuntu based ones, still using `industrial_ci`.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Github configuration still requires Travis to succeed, so I'll remove that and we can merge the PR.

**Review by jontje — APPROVED** [review]
Looks good to me 👍

**Comment by gavanderhoorn** [comment]
Thanks @jontje.

**Comment by gavanderhoorn** [comment]
Final note: the Xenial+Kinetic builds have been removed.

ROS Kinetic is almost EOL, so we're not testing that any more.

It will most likely continue to work, but we can't guarantee it.

Bionic and newer also don't need the custom Poco install any more, which simplifies the build config as well.

**Pull request merged**
