### PR TITLE
feature/InstallSpaceUpdate

### PR DESCRIPTION
**Pull request by colin-lewis-ut**
minor fix to install space

### CODE REVIEW

**Comment by jontje** [comment]
Thanks for the PR @colin-lewis-ut, and sorry for the slow response!

Would you mind making your branch up-to-date with the base branch?

**Comment by colin-lewis-ut** [comment]
This should be up to date with master now

**Comment by simonschmeisser** [comment]
@jontje this looks good and should be merged :)

**Comment by jontje** [comment]
I have forgotten to let you know that PR https://github.com/ros-industrial/abb_librws/pull/69, which was created after my last comment, will turn this library into a plain cmake package. That PR includes an adoption of the correct install space fix.

**Pull request closed without merging**
