### PR TITLE
travis: add Foxy CI build

### PR DESCRIPTION
**Pull request by mvegter**
Added latest ROS2 distribution.

### CODE REVIEW

**Comment by jontje** [comment]
@mvegter, can you update your branch with the latest changes?

**Comment by gavanderhoorn** [comment]
Suggestion please rebase if possible. Let's not complicate history more than necessary.

**Comment by mvegter** [comment]
@jontje, @gavanderhoorn done!

**Review by jontje — APPROVED** [review]
Looks good to me

**Comment by jontje** [comment]
Thanks for the PR @mvegter 👍

**Pull request merged**
