### PR TITLE
Fix nested rapid records copy

### PR DESCRIPTION
**Pull request by jontje**
Adds copy constructors to the RAPID record representations, to be able to copy nestled instances.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
So I've delayed reviewing this as I'm not exactly clear on whether the copy ctors are all needed.

Are there non-PODs here? Or pointers to objects as member variables?

**Comment by jontje** [comment]
> So I've delayed reviewing this as I'm not exactly clear on whether the copy ctors are all needed.

They are needed due to how the RAPID `RECORD` data type is represented here, which is an attempt to emulate the data type definitions of RAPID:

> - An atomic type is atomic in the sense that it is not defined based on any other type and cannot be divided into parts or components, for example num.
> 
> - A record data type is a composite type with named, ordered components, for example pos. A component may be of an atomic or record type.
> A record value can be expressed using an aggregate representation, for example [ 300, 500, depth ] pos record aggregate value.
> A specific component of a record data can be accessed by using the name of that component, for example pos1.x := 300; assignment of the x-component of pos1.

The [RAPIDRecord](https://github.com/ros-industrial/abb_librws/blob/3f980c8ec4621f3f7ede5c206268717ac19a9689/include/abb_librws/rws_rapid.h#L275) implementation uses a vector of raw pointers for "ordering" its data members, as well as being able to consist of both `RAPIDAtomic` and `RAPIDRecord` components. The constructors take care of putting the data members, into the components vector, in the correct order.

Without the copy constructors, then I get errors when I for example use the copy assignment operator between vectors of `RAPIDRecord`s. I.e. due to the components vector (of raw pointers) not properly taken care of.

> Are there non-PODs here? Or pointers to objects as member variables?

Both.

**Review by gavanderhoorn — APPROVED** [review]
Not sure there isn't a way to do this without storing pointers, but that would be something out of scope for this PR.

**Comment by gavanderhoorn** [comment]
@jontje: if you could rebase your PR on-top of `master`, I'll resubmit the review and we get to keep linear-ish history.

**Comment by jontje** [comment]
> @jontje: if you could rebase your PR on-top of `master`, I'll resubmit the review and we get to keep linear-ish history.

Done.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
As soon as Travis is happy, we can merge.

**Comment by jontje** [comment]
> As soon as Travis is happy, we can merge.

Great, thanks for the PR 👍

**Pull request merged**
