### PR TITLE
Collect mech unit group cfg instances

### PR DESCRIPTION
**Pull request by jontje**
As per title

### CODE REVIEW

**Comment by jontje** [comment]
Synced with base branch and added error handling.

I also fixed a few mistakes I had made when processing merge conflicts in previous PRs (#112 - #118), since this is the last PR in that batch.

**Comment by gavanderhoorn** [comment]
Why not squash the fixup commits into the previous ones? No need for those to end up in the history.

**Comment by jontje** [comment]
> Why not squash the fixup commits into the previous ones? No need for those to end up in the history.

I don't think I have ever used `squash` in `git`, so it didn't even cross my mind.


> Edit: oh, wait. Those changes are to 'other' files, correct?

Yes, I only moved some function definitions around in be8cc90 (no changes to the actual implementation).

**Review by gavanderhoorn — APPROVED** [review]
This was a bit difficult to review, due to the fixup commit "in the middle".

But I believe this looks OK.

It's at least in-line with the other recent additions.

**Comment by jontje** [comment]
Thanks for the review @gavanderhoorn 👍

**Pull request merged**
